# Exploring Poverty vs Non-Profit Support in Washington 
###
This Notebook will be used to clean, preprocess, and analyze data sets that reflect Washington's populations by county, Non-profits currently supporting Washington's communities, and a crosswalk to connect my two data sets. 

created by: Amie Browder

## Data:
In this notebook, we will examine three data frames sourced from various public government websites. 

#### Non-profit data (eo_wa.csv):
https://www.irs.gov/charities-non-profits/exempt-organizations-business-master-file-extract-eo-bmf#states

This data was collected from the IRS website and is the Exempt Organizations Business Master File Extract (EO BMF) for Washington State. The data frame shows the different active non-profits in Washington state, their location, the type of non-profits, and other tax information that will not be needed for the project. 


#### Location Crosswalk(    ): 
https://www.huduser.gov/apps/public/uspscrosswalk/hom

This data was collected from the Office of Policy Development and Research website, provided by HUD and USPS in combination. The file shows the zip, geoid, city, and state, as well as a few other identifiers that will not be used. This file will be used to combine my two data sets as one contains zip codes and the other contains county information.


#### Poverty Data (ACSST5Y2023.S1701-Data.csv):
https://data.census.gov/table?t=Poverty&g=040XX00US53$0500000

This dataset was obtained from the United States Census Bureau via the S1701 American Community Survey. This Table shows demographic information for the different counties in Washington State. This data includes items such as poverty, employment, insurance, income, education level, and other data that will not be used in the project. e

In [7]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt

In [13]:
#importing the non-profit data set
nf_df = pd.read_csv('Non-forprofit Data/eo_wa.csv')

#checking to ensure that it downloaded 
nf_df.head()

,EIN,NAME,ICO,STREET,CITY,STATE,ZIP,GROUP,SUBSECTION,AFFILIATION,...,ASSET_CD,INCOME_CD,FILING_REQ_CD,PF_FILING_REQ_CD,ACCT_PD,ASSET_AMT,INCOME_AMT,REVENUE_AMT,NTEE_CD,SORT_NAME
0,10555614,OKANOGAN REGIONAL HUMANE,% TINA GERMANO-DELAP,398 OMAK RIVER ROAD,OMAK,WA,98841-0000,0,3,3,...,5,4,1,0,12,658857.0,281666.0,281666.0,D20,NaN
1,10566082,OROMO CULTURAL CENTER,% ADAM TAHIR,8819 RENTON AVE S,SEATTLE,WA,98118-4918,0,3,3,...,0,0,2,0,12,0.0,0.0,0.0,A23,NaN
2,10568603,GLOBAL GATEWAY NETWORK,% MICAH A SMITH,PO BOX 141,NINE MILE FLS,WA,99026-0141,0,3,3,...,4,4,1,0,12,286941.0,223385.0,223385.0,X20,NaN
3,10573492,SW WASHINGTON HIGH TECHNOLOGY COUNCIL,% CASEY ODELL,PO BOX 871496,VANCOUVER,WA,98687-1496,0,6,3,...,0,0,2,0,12,0.0,0.0,0.0,S41,NaN
4,10585828,VANCOUVER LAKE CREW,% NANCY STREBE,13612 NW 44TH CT,VANCOUVER,WA,98685-1529,0,3,3,...,4,4,1,0,12,111870.0,356187.0,317345.0,N67,NaN

In [14]:
#importing the Poverty Data set 
p_df = pd.read_csv('Poverty Data/ACSST5Y2023.S1701-Data.csv')

p_df.head(5)

,GEO_ID,NAME,S1701_C01_001E,S1701_C01_001M,S1701_C01_002E,S1701_C01_002M,S1701_C01_003E,S1701_C01_003M,S1701_C01_004E,S1701_C01_004M,...,S1701_C03_058M,S1701_C03_059E,S1701_C03_059M,S1701_C03_060E,S1701_C03_060M,S1701_C03_061E,S1701_C03_061M,S1701_C03_062E,S1701_C03_062M,Unnamed: 374
0,Geography,Geographic Area Name,Estimate!!Total!!Population for whom poverty s...,Margin of Error!!Total!!Population for whom po...,Estimate!!Total!!Population for whom poverty s...,Margin of Error!!Total!!Population for whom po...,Estimate!!Total!!Population for whom poverty s...,Margin of Error!!Total!!Population for whom po...,Estimate!!Total!!Population for whom poverty s...,Margin of Error!!Total!!Population for whom po...,...,Margin of Error!!Percent below poverty level!!...,Estimate!!Percent below poverty level!!UNRELAT...,Margin of Error!!Percent below poverty level!!...,Estimate!!Percent below poverty level!!UNRELAT...,Margin of Error!!Percent below poverty level!!...,Estimate!!Percent below poverty level!!UNRELAT...,Margin of Error!!Percent below poverty level!!...,Estimate!!Percent below poverty level!!UNRELAT...,Margin of Error!!Percent below poverty level!!...,NaN
1,0500000US53001,"Adams County, Washington",20494,44,7238,69,1810,8,5428,70,...,(X),10.8,9.5,45.4,14.1,46.4,10.2,20.3,3.8,NaN
2,0500000US53003,"Asotin County, Washington",22209,42,4360,123,1276,124,3084,134,...,(X),3.2,3.2,37.9,8.1,39.8,6.2,14.9,2.1,NaN
3,0500000US53005,"Benton County, Washington",208077,326,54406,332,13420,101,40986,309,...,(X),1.5,0.8,24.8,4.8,37.4,4.1,10.8,1.1,NaN
4,0500000US53007,"Chelan County, Washington",78619,162,17842,168,4367,122,13475,164,...,(X),2.9,1.5,22.2,7.3,36.8,5.3,8.4,1.3,NaN